[package]
name = "appflowy-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace.dependencies]
anyhow = "1.0.75"
tracing = "0.1.40"
bytes = "1.5.0"
protobuf = { version = "2.28.0" }
diesel = { version = "2.1.0", features = ["sqlite", "chrono", "r2d2"] }
uuid = { version = "1.5.0", features = ["serde", "v4"] }
serde_repr = "0.1"
parking_lot = "0.12"
futures = "0.3.29"
tokio = "1.34.0"
tokio-stream = "0.1.14"
async-trait = "0.1.74"
chrono = { version = "0.4.31", default-features = false, features = ["clock"] }
lru = "0.12.0"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.24"
web-sys = "0.3.45"
lazy_static = "1.4.0"
bytes.workspace = true
tracing.workspace = true
js-sys = "0.3.66"
serde-wasm-bindgen = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getrandom = { version = "0.2", features = ["js"] }
lib-dispatch = { path = "../../rust-lib/lib-dispatch", features = ["use_serde"] }
flowy-notification = { path = "../../rust-lib/flowy-notification", features = ["ts"] }
